CREATE DATABASE DATA_ANALYSIS_PROJECT;
USE data_analysis_project;

-- // Business Insight Questions \\ --

-- 1. Which category generates highest revenue?
SELECT category, ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM shopping_data GROUP BY category
ORDER BY highest_revenue DESC;

-- 2. Are discount actually increasing purchase value?

SELECT discount_applied, 
ROUND(SUM(purchase_amount),2) AS highest_revenue, 
ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM shopping_data GROUP BY discount_applied;
    
-- 3. What is the Total revenue generated by male and female customer?

SELECT gender, ROUND(SUM(purchase_amount),2) AS revenue
FROM shopping_data GROUP BY gender;

-- 4. Which customer used a discount but still spent more than the average purchase amount?

select  customer_id, round(purchase_amount,2) as purchase_amount, discount_applied
from shopping_data where discount_applied = "Yes" and purchase_amount > 
(select avg(purchase_amount) from shopping_data) order by purchase_amount Desc limit 10;

-- 5. Which are the top/bottom 5 products with the highest average review rating?
-- top 5
select * from shopping_data;
select  item_purchased, round(avg(review_rating),2 ) as Avg_ratings 
from shopping_data group by item_purchased order by Avg_ratings desc limit 5;

-- bottom 5

select  item_purchased, round(avg(review_rating),2 ) as Avg_ratings 
from shopping_data group by item_purchased order by Avg_ratings asc limit 5;

-- 6. Average purchase: Standard vs Express shiping

select * from shopping_data;
select 
Shipping_type, count(distinct customer_id) as order_placed,
round(avg(purchase_amount),2) as avg_purchase
from shopping_data where Shipping_type in ('Standard','Express') group by Shipping_type;

-- 7. Do subscribed customer spend more? Compare average speed and total revenue between subscribers and non-subscribers.
select * from shopping_data;
select count(customer_id) as users, subscription_status, round(sum(purchase_amount)) as total_spend,
round(avg(purchase_amount)) as avg_spend from shopping_data group by subscription_status;


-- 8. Top 5 products with highest discount usage %

select item_purchased, 
count(item_purchased) as total_numbers_of_times_sold, 
count(case when discount_applied = 'Yes' then 1 end ) as Is_dicount_apply,
count(case when discount_applied = 'Yes' then 1 end ) *100/count(*) as discount_percent 
from shopping_data
group by item_purchased order by item_purchased desc
;


-- 9. Segment customers Into new, returning and loyal based on their 
--  total number of previous purchase, and show the each segment.

select * from shopping_data;

select case
	when previous_purchases = 0 Then 'New Customer'
	when previous_purchases between 1 and 15 Then 'Returning Customer'
    else 'Loyal Customers' end as 'Customer Segment',
    count(*) as Customer_Count from  shopping_data
    group by case
    when previous_purchases = 0 Then 'New Customer'
    when previous_purchases between 1 and 15 Then 'Returning Customer'
    else 'Loyal Customers' end;
    
    
    -- 10. What are the top 3 most purchased products within each category?
    
    with cte as(
    select category, item_purchased, count(item_purchased) as most_purchased,
    rank() over(partition by category order by count(item_purchased) desc) as rnk
    from shopping_data group by category, item_purchased
) select * from cte  where rnk<=3;

-- 12. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

select case
			when previous_purchases > 5 then 'Repeat Buyers'
            else 'Normal Buyers' end as customer_type, subscription_status,
            count(*) as customer_type
            from shopping_data group by case
            when previous_purchases>5 then 'Repeat Buyers'
            else 'Normal Buyers'
            end, subscription_status;


-- 12. What is the revenue contribution of each age group?


select case
			when age between 18 and 25 then '18-25'
			when age between 26 and 35 then '26-35'
			when age between 36 and 50 then '36-50'
			else '51+'
		end as age_group,
		round(sum(purchase_amount),2) as total_revenue
from shopping_data 
group by case
			when age between 18 and 25 then '18-25'
			when age between 26 and 35 then '26-35'
			when age between 36 and 50 then '36-50'
			else '51+'
		end 
        order by total_revenue desc;


