-- ============================================================
--        CUSTOMER SHOPPING BEHAVIOUR ANALYSIS
--        Phase 2 : SQL Business Insights
-- ============================================================
-- Project   : Customer Behaviour Analysis
-- Database  : data_analysis_project
-- Table     : shopping_data  (imported from Python/Pandas phase)
-- Tool      : MySQL
-- Author    : Khan  (MCA Section-B, KIET University)
-- Workflow  : Python (EDA + Cleaning) → SQL (Analysis) → Power BI (Dashboard)
-- ============================================================


-- ─────────────────────────────────────────
-- DATABASE SETUP
-- ─────────────────────────────────────────

-- Create the project database (run only once)
CREATE DATABASE DATA_ANALYSIS_PROJECT;

-- Select the database to use for all following queries
USE data_analysis_project;


-- ============================================================
-- // BUSINESS INSIGHT QUESTIONS \\
-- ============================================================


-- ─────────────────────────────────────────────────────────────
-- Q1. Which category generates the highest revenue?
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Identify which product category contributes most to total revenue.
-- Use Case : Helps in deciding where to focus marketing and inventory budget.
-- Method   : SUM of purchase_amount grouped by category, sorted high to low.
-- ─────────────────────────────────────────────────────────────

SELECT 
    category, 
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM shopping_data
GROUP BY category
ORDER BY total_revenue DESC;


-- ─────────────────────────────────────────────────────────────
-- Q2. Are discounts actually increasing purchase value?
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Compare total and average purchase amounts between
--            customers who received a discount vs those who didn't.
-- Use Case : Evaluate the effectiveness of the discount strategy.
-- Method   : GROUP BY discount_applied (Yes / No), compare SUM and AVG.
-- ─────────────────────────────────────────────────────────────

SELECT 
    discount_applied, 
    ROUND(SUM(purchase_amount), 2)  AS total_revenue, 
    ROUND(AVG(purchase_amount), 2)  AS avg_purchase
FROM shopping_data
GROUP BY discount_applied;


-- ─────────────────────────────────────────────────────────────
-- Q3. What is the total revenue generated by male and female customers?
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Understand revenue split between genders.
-- Use Case : Useful for gender-targeted marketing campaigns.
-- Method   : SUM of purchase_amount grouped by gender.
-- ─────────────────────────────────────────────────────────────

SELECT 
    gender, 
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM shopping_data
GROUP BY gender;


-- ─────────────────────────────────────────────────────────────
-- Q4. Which customers used a discount but still spent more than average?
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Find high-value customers who applied discounts yet
--            spent above the overall average purchase amount.
-- Use Case : These customers are profitable even with discounts —
--            ideal targets for loyalty programs or premium offers.
-- Method   : Subquery calculates global average; outer query filters
--            discount users who exceed that average. Top 10 shown.
-- ─────────────────────────────────────────────────────────────

SELECT 
    customer_id, 
    ROUND(purchase_amount, 2) AS purchase_amount, 
    discount_applied
FROM shopping_data
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM shopping_data)
ORDER BY purchase_amount DESC
LIMIT 10;


-- ─────────────────────────────────────────────────────────────
-- Q5. Top 5 and Bottom 5 products by average review rating
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Identify best-rated and worst-rated products.
-- Use Case : Top 5 → highlight in promotions.
--            Bottom 5 → investigate quality or service issues.
-- Method   : AVG of review_rating per item, sorted DESC (top) / ASC (bottom).
-- ─────────────────────────────────────────────────────────────

-- Top 5 highest rated products
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Bottom 5 lowest rated products
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_rating ASC
LIMIT 5;


-- ─────────────────────────────────────────────────────────────
-- Q6. Average purchase amount: Standard vs Express shipping
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Compare order volume and average spend between Standard
--            and Express shipping customers.
-- Use Case : Helps pricing logistics and understanding if premium
--            shipping attracts higher-spending customers.
-- Method   : Filter only Standard and Express; GROUP BY shipping_type.
-- ─────────────────────────────────────────────────────────────

SELECT 
    shipping_type, 
    COUNT(DISTINCT customer_id) AS orders_placed,
    ROUND(AVG(purchase_amount), 2)  AS avg_purchase
FROM shopping_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- ─────────────────────────────────────────────────────────────
-- Q7. Do subscribed customers spend more?
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Compare total and average spend between subscribers
--            and non-subscribers.
-- Use Case : Helps evaluate whether the subscription program drives
--            higher customer lifetime value (CLV).
-- Method   : GROUP BY subscription_status (Yes / No).
-- ─────────────────────────────────────────────────────────────

SELECT 
    subscription_status,
    COUNT(customer_id)              AS total_users,
    ROUND(SUM(purchase_amount))     AS total_spend,
    ROUND(AVG(purchase_amount))     AS avg_spend
FROM shopping_data
GROUP BY subscription_status;


-- ─────────────────────────────────────────────────────────────
-- Q8. Top 5 products with highest discount usage percentage
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Find which products are most frequently sold with a discount.
-- Use Case : Identifies products that rely heavily on discounts —
--            may indicate pricing issues or high competition.
-- Method   : CASE WHEN counts discount applications per item,
--            divided by total sales × 100 to get percentage.
--            Sorted by discount_percent DESC and limited to top 5.
-- NOTE     : Original query had ORDER BY item_purchased DESC (wrong).
--            Fixed to ORDER BY discount_percent DESC to get correct top 5.
-- ─────────────────────────────────────────────────────────────

SELECT 
    item_purchased, 
    COUNT(item_purchased)                                              AS total_times_sold,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END)              AS discount_used_count,
    ROUND(
        COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*), 2
    )                                                                  AS discount_percent
FROM shopping_data
GROUP BY item_purchased
ORDER BY discount_percent DESC
LIMIT 5;


-- ─────────────────────────────────────────────────────────────
-- Q9. Segment customers into New, Returning, and Loyal
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Classify customers based on their purchase history.
-- Use Case : Each segment needs a different marketing approach:
--            New       → acquisition offers, onboarding emails
--            Returning → re-engagement campaigns
--            Loyal     → VIP rewards, referral programs
-- Segments :
--   New Customer      → 0 previous purchases
--   Returning Customer → 1 to 15 previous purchases
--   Loyal Customer    → more than 15 previous purchases
-- ─────────────────────────────────────────────────────────────

SELECT 
    CASE
        WHEN previous_purchases = 0           THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM shopping_data
GROUP BY 
    CASE
        WHEN previous_purchases = 0           THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END;


-- ─────────────────────────────────────────────────────────────
-- Q10. Top 3 most purchased products within each category
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Find best-selling products inside every category.
-- Use Case : Inventory planning — know which products to stock more.
-- Method   : CTE + Window Function (RANK partitioned by category).
--            RANK() assigns rank 1 to the most purchased item per category.
--            Outer query filters where rank <= 3.
-- ─────────────────────────────────────────────────────────────

WITH ranked_products AS (
    SELECT 
        category, 
        item_purchased, 
        COUNT(item_purchased)                                       AS purchase_count,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS rnk
    FROM shopping_data
    GROUP BY category, item_purchased
)
SELECT 
    category, 
    item_purchased, 
    purchase_count, 
    rnk AS rank_within_category
FROM ranked_products
WHERE rnk <= 3
ORDER BY category, rnk;


-- ─────────────────────────────────────────────────────────────
-- Q11. Are repeat buyers (> 5 purchases) more likely to subscribe?
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Check if customers with more purchase history tend
--            to be subscribers more often.
-- Use Case : If repeat buyers subscribe more → loyalty program
--            drives subscriptions. Target them with subscription offers.
-- Method   : CASE classifies buyers; cross-tabulation with subscription_status.
-- NOTE     : This was numbered Q12 in original file (duplicate number).
--            Renumbered to Q11 for correct sequence.
-- ─────────────────────────────────────────────────────────────

SELECT 
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END AS customer_type,
    subscription_status,
    COUNT(*) AS customer_count
FROM shopping_data
GROUP BY 
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END, 
    subscription_status
ORDER BY customer_type, subscription_status;


-- ─────────────────────────────────────────────────────────────
-- Q12. What is the revenue contribution of each age group?
-- ─────────────────────────────────────────────────────────────
-- Purpose  : Identify which age demographic generates the most revenue.
-- Use Case : Helps in creating age-targeted ads and product placement.
-- Age Groups:
--   18–25  → Young Adults / Students
--   26–35  → Working Professionals
--   36–50  → Mid-career / Family buyers
--   51+    → Senior customers
-- Method   : CASE bucketing on age column, SUM of purchase_amount.
-- ─────────────────────────────────────────────────────────────

SELECT 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25 (Young Adults)'
        WHEN age BETWEEN 26 AND 35 THEN '26-35 (Working Professionals)'
        WHEN age BETWEEN 36 AND 50 THEN '36-50 (Mid-career)'
        ELSE '51+ (Senior)'
    END AS age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM shopping_data
GROUP BY 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25 (Young Adults)'
        WHEN age BETWEEN 26 AND 35 THEN '26-35 (Working Professionals)'
        WHEN age BETWEEN 36 AND 50 THEN '36-50 (Mid-career)'
        ELSE '51+ (Senior)'
    END
ORDER BY total_revenue DESC;


-- ============================================================
-- END OF ANALYSIS
-- ============================================================
-- Summary of queries:
--  Q1  Revenue by Category
--  Q2  Discount Impact on Purchase Value
--  Q3  Revenue by Gender
--  Q4  High-Value Discount Users (Subquery)
--  Q5  Top & Bottom 5 Products by Rating
--  Q6  Standard vs Express Shipping
--  Q7  Subscriber vs Non-Subscriber Spend
--  Q8  Top 5 Discount-Heavy Products
--  Q9  Customer Segmentation (New / Returning / Loyal)
--  Q10 Top 3 Products per Category (CTE + Window Function)
--  Q11 Repeat Buyers & Subscription Correlation
--  Q12 Revenue by Age Group
-- ============================================================
